name: Publish package on mozilla

on:
  push:
    branches:
     - master
     - test_workflow

jobs:
  create-tag:
    name: Check version change
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: check_version
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GH_TOKEN }}
        run: |
          if git diff-tree --patch --raw  HEAD HEAD~1 public/manifest.json | grep "\-  \"version\""
          then
            echo Version changed
            new_version=$(cat public/manifest.json | grep -Po '"version\": \"\K[^"]*')
            echo new_version $new_version
            echo "new_version=${new_version}" >> $GITHUB_OUTPUT
            echo "status=success" >> $GITHUB_OUTPUT
            # curl \
            #   -X POST \
            #   -H "Accept: application/vnd.github+json" \
            #   -H "Authorization: Bearer $GITHUB_TOKEN"\
            #   -H "X-GitHub-Api-Version: 2022-11-28" \
            #   https://api.github.com/repos/sapristi/journal-startpage/git/tags \
            #   -d '{"tag":"${new_version}","message":"version ${new_version}","object":"${GITHUB_SHA}","type":"commit","tagger":{"name":"Mathias Millet","email":"noreply@github.com"}}' \
            #   --fail
          else
            echo Version did not change
            echo "status=failure" >> $GITHUB_OUTPUT
          fi
      - uses: actions/setup-python@v4
      - uses: jannekem/run-python-script-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GH_TOKEN }}
        with:
          script: |
            import os
            token = os.environ["GITHUB_TOKEN"]
            print(len(token))
            l = len(token)
            print(l)



