name: Publish package on mozilla

on:
  push:
    branches:
     - master
     - test_workflow

jobs:
  create-tag:
    name: create tag
    runs-on: ubuntu-latest
    steps:
      # - name: "Checkout"
      #   uses: actions/checkout@v3
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"

