name: Publish package on mozilla

on:
  push:
    branches:
     - master
     - test_workflow

jobs:
  create-tag:
    name: Check version change
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: check_version
        run: |
          set -e
          git diff-tree --patch --raw  HEAD HEAD~1 public/manifest.json | grep "\-  \"version\""
          if [ $? = 0 ]
          then
            echo Version changed
            new_version=$(cat public/manifest.json | grep -Po '"version\": \"\K[^"]*')
            echo new_version $new_version
            echo "new_version=${new_version}" >> $GITHUB_OUTPUT
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.check_version.outputs.new_version }} == 'success'
        with:
          tag: ${{ steps.check_version.outputs.new_version }}
          message: "Latest release"

